/* Published copy: the local papers/ folder is not deployed, so hide local PDF links. */
window.LOCAL_PDFS = false;

/* Literature data. Plain global so the site works from file:// with no server. */

window.META = {
  title: "Heterogeneous Robot Planning & Learning",
  subtitle: "Learning and planning across heterogeneous robot teams — a working literature review",
  compiled: "2026-09-16",
  source: "ChatGPT deep-research session “Heterogeneous Robot Planning”",
  note: "Every title, author list, year and identifier was re-verified against the arXiv API or publisher page before download. Per-paper descriptions come from the research session and have not been re-derived from a full reading of each PDF — confirm against the PDFs as you read."
};

window.THREADS = {
  "async":      { label: "Asynchronous macro-action RL", color: "#2563eb",
                  blurb: "Learning coordination policies over skills that start and finish at different times. The methodological core of the proposed project." },
  "alloc":      { label: "Allocation & scheduling",      color: "#7c3aed",
                  blurb: "Deciding which robot (or coalition) performs an already-specified task, with capabilities, durations and sometimes precedence." },
  "options":    { label: "Options & temporal abstraction", color: "#0891b2",
                  blurb: "The formal machinery that turns a whole skill into a single RL action." },
  "aerial":     { label: "Aerial–ground systems",         color: "#059669",
                  blurb: "Drones providing perception or coverage that changes what ground robots do." },
  "simreal":    { label: "Sim-to-real heterogeneous RL",  color: "#ea580c",
                  blurb: "Policies trained in a physics simulator and then run on physical robots with genuinely different capabilities." },
  "llm":        { label: "LLM coordination",             color: "#db2777",
                  blurb: "Heterogeneous task decomposition driven by prompted language models rather than learning." },
  "arch":       { label: "Policy architecture",          color: "#ca8a04",
                  blurb: "How to parameterise policies so different robots behave differently and generalise to new teams." },
  "tamp":       { label: "Task & motion planning",       color: "#475569",
                  blurb: "Symbolic / formal-specification routes to the same coordination problem." },
  "systems":    { label: "Systems",                      color: "#64748b",
                  blurb: "Infrastructure-level views of heterogeneous teams." }
};


/* ── classification taxonomy: heterogeneity → application → learning method ── */
window.HET = {
  yes:    {label:"Uses heterogeneous robots", color:"#2f5bd8"},
  no:     {label:"Homogeneous team or single agent", color:"#64748b"},
  unclear:{label:"Needs checking", color:"#b45309"}
};
window.HETKIND = {
  physical:   {label:"Physical / morphological", blurb:"Different bodies: aerial vs ground, arm vs mobile base, quadruped vs quadrotor. The capability gap is structural and cannot be reassigned."},
  capability: {label:"Capability / trait vectors", blurb:"Similar or abstract platforms carrying different skill sets, attachments or trait vectors. Heterogeneity is a parameter, which is what makes transfer experiments possible."},
  role:       {label:"Functional role", blurb:"Robots differentiated by the job they hold in the team — pursuer, observer, communication relay — rather than by their body."},
  none:       {label:"—", blurb:""}
};
window.APPS = {
  sar:        {label:"Search & rescue", blurb:"Find victims or targets under time pressure and retrieve them.", color:"#dc2626"},
  logistics:  {label:"Warehouse & tool delivery", blurb:"Fetch, stage and hand over objects so another agent can keep working.", color:"#2563eb"},
  transport:  {label:"Object transport & foraging", blurb:"Move many objects to a collection area, exploiting complementary manipulation abilities.", color:"#7c3aed"},
  assembly:   {label:"Construction & assembly", blurb:"Place objects into a specified configuration, often with ordering constraints.", color:"#059669"},
  household:  {label:"Household & everyday tasks", blurb:"Long-horizon instruction following in furnished indoor scenes.", color:"#db2777"},
  inspect:    {label:"Inspection, mapping & exploration", blurb:"Cover an area and build a map or report — the information-gathering end of the spectrum.", color:"#0891b2"},
  pursuit:    {label:"Pursuit & tracking", blurb:"Catch or track a moving target under sensing and communication constraints.", color:"#ea580c"},
  herding:    {label:"Shepherding & herding", blurb:"Drive a group of uncontrolled agents toward a goal region.", color:"#65a30d"},
  navigation: {label:"Constrained navigation", blurb:"Get physically different robots through space that does not fit them equally.", color:"#0d9488"},
  alloc:      {label:"Abstract allocation & scheduling", blurb:"No physical task — synthetic robot/task instances used to benchmark the allocator itself.", color:"#6b7280"},
  generalise: {label:"Capability-generalisation benchmarks", blurb:"Tasks designed to test transfer to unseen team compositions rather than to be realistic.", color:"#ca8a04"},
  field:      {label:"Field operations & shared compute", blurb:"Heterogeneity in sensing, bandwidth and computation rather than actuation.", color:"#78716c"},
  search:     {label:"Target localisation", blurb:"Decide who searches where, with detection as the objective.", color:"#c026d3"},
  theory:     {label:"Theory & benchmark domains", blurb:"Gridworlds, Pinball, Atari — used to establish a framework, not an application.", color:"#94a3b8"}
};
window.METHODS = {
  none:       {label:"No learning — planning / optimisation / formal methods", short:"No learning", blurb:"Heuristic search, MILP, or temporal-logic synthesis. The capability model is given.", color:"#64748b"},
  macroac:    {label:"Actor–critic MARL over macro-actions", short:"Macro-action actor–critic", blurb:"Policy-gradient methods whose value updates respect that each robot's skill has its own duration.", color:"#2563eb"},
  valuerl:    {label:"Value-based deep MARL (DQN / DRQN)", short:"Value-based deep MARL", blurb:"Q-learning over temporally extended or spatial action spaces.", color:"#7c3aed"},
  attn:       {label:"Attention / graph networks trained with RL", short:"Attention/GNN + RL", blurb:"Encoder–decoder or GNN policies that emit the next assignment, trained with policy gradient.", color:"#0891b2"},
  imitation:  {label:"Imitation learning from a solver", short:"Imitation learning", blurb:"Supervised cloning of an optimal or near-optimal schedule; fast at run time, bounded by the expert.", color:"#db2777"},
  hrl:        {label:"Hierarchical RL", short:"Hierarchical RL", blurb:"An explicit manager/worker split, with sub-behaviours learned or fixed.", color:"#059669"},
  selfplay:   {label:"Self-play & curriculum MARL", short:"Self-play MARL", blurb:"Opponents and task difficulty are generated during training rather than fixed.", color:"#ea580c"},
  ppognn:     {label:"PPO with per-agent parameters + GNN communication", short:"PPO + GNN comms", blurb:"Behavioural specialisation bought by giving each robot its own parameters.", color:"#ca8a04"},
  hyper:      {label:"Capability-conditioned hypernetworks", short:"Hypernetworks", blurb:"One shared network generates each robot's weights from its capability vector.", color:"#c026d3"},
  em:         {label:"EM-based policy search over finite-state controllers", short:"EM over FSCs", blurb:"Fits small memory-bearing controllers from sampled trajectories — no gradients.", color:"#0d9488"},
  model:      {label:"Supervised model learning inside a planner", short:"Learned model in planner", blurb:"Learn capabilities, requirements or task efficacy, then hand them to a classical optimiser.", color:"#65a30d"},
  perception: {label:"Learned perception only", short:"Learned perception", blurb:"Segmentation or mapping models are learned; the policy is not.", color:"#78716c"},
  llm:        {label:"LLM prompting, no training", short:"LLM prompting", blurb:"A language model decomposes and assigns subtasks; execution feedback drives replanning.", color:"#dc2626"},
  finetune:   {label:"Fine-tuned VLM / LLM", short:"Fine-tuned VLM/LLM", blurb:"Supervised fine-tuning of a perception or reasoning model; the planner itself is not trained.", color:"#f43f5e"},
  theory:     {label:"RL theory & temporal abstraction", short:"RL theory", blurb:"Frameworks and algorithms for options, not an application result.", color:"#94a3b8"}
};

window.PAPERS = [
/* ─────────────────────────────  TIER A  ───────────────────────────── */
{
  id:"A10", tier:"A", thread:"async", relevance:5, order:2,
  title:"Asynchronous Actor-Critic for Multi-Agent Reinforcement Learning",
  authors:"Yuchen Xiao, Weihao Tan, Christopher Amato",
  year:2022, venue:"NeurIPS 2022",
  het:"yes", hetKind:"physical", appKey:"logistics", methodKey:"macroac",
  cite:"Xiao et al., NeurIPS 2022", bibkey:"xiao2022asynchronous",
  gist:"Mac-IAICC learns decentralised policies over predefined macro-actions, with each robot's critic updated on its own action duration. Fetch + 2 TurtleBots.",
  useFor:"Your main methodological reference and closest baseline for learning coordination above existing controllers with asynchronous skill durations.",
  url:"https://arxiv.org/abs/2209.10113", pdf:"A10_AsyncActorCritic_Xiao_NeurIPS2022.pdf",
  code:"", badge:"Start here",
  platforms:"Fetch manipulator + 2 TurtleBots",
  simulator:"Abstract simulation (not physics-level)",
  hardware:"Yes — learned policies deployed on real robots",
  rl:"Yes",
  learned:"Decentralized policies <em>over predefined macro-actions</em>. Mac-IAICC gives each robot its own centralized critic during training, with value updates aligned to that robot's own action duration.",
  supplied:"Navigation and manipulation controllers (ROS nav + manipulation stack). Only the coordination layer above them is learned.",
  summary:"A Fetch arm and two TurtleBots deliver tools to people assembling furniture. Fetch finds and hands over tools; the TurtleBots carry them. The team must choose which tools to prepare, whom to serve, and when to move or wait — and because navigation and manipulation finish at different times, the decision points are inherently asynchronous.",
  why:"This is the closest methodological match to the proposed project: learning a coordination policy on top of controllers you already have, with genuinely asynchronous skill durations, demonstrated on real hardware.",
  caveats:["Task-policy training uses an abstract simulation rather than Gazebo-level physics.","The macro-actions themselves are hand-designed, not discovered."],
  reading:"Read Sections 3–5 first, then Appendix F for the hardware implementation.",
  figures:[{
    src:"A10_behaviors.png", label:"Figure 5 — Collaborative behaviours learned by Mac-IAICC",
    caption:"Collaborative behaviors generated by running the decentralized policies learned by Mac-IAICC, where Turtlebot-0 is bounded in red and Turtlebot-1 in blue.",
    explain:"Four frames of the real tool-delivery run, left to right. The Fetch arm (white, left of each frame) works at the tool table while the two TurtleBots (boxed red and blue) move independently around the room. What matters is what the frames show <em>between</em> them: in (a) the Fetch has already staged a tool and one TurtleBot is en route, so the arm is not idling while a carrier travels. By (b)–(c) the two carriers are at different stages of different errands — one is being loaded while the other is already delivering. That staggering is the whole point. A synchronous formulation would force both carriers onto the same decision clock and lose it; the duration-aligned critic is what lets each robot commit to a long skill while the others keep acting."
  }]
},
{
  id:"A11", tier:"A", thread:"async", relevance:5, order:3,
  title:"Learning for Multi-robot Cooperation in Partially Observable Stochastic Environments with Macro-actions",
  authors:"Miao Liu, Kavinayan Sivakumar, Shayegan Omidshafiei, Christopher Amato, Jonathan P. How",
  year:2017, venue:"IROS 2017",
  het:"yes", hetKind:"physical", appKey:"sar", methodKey:"em",
  cite:"Liu et al., IROS 2017", bibkey:"liu2017learning",
  gist:"Learns finite-state controllers over heterogeneous macro-actions under partial observability; a UAV surveys while three ground robots retrieve victims.",
  useFor:"The key precedent for a drone gathering information that changes ground-robot decisions. Cite it, and note the pickup is simulated.",
  url:"https://arxiv.org/abs/1707.07399", pdf:"A11_MacroActionFSC_Liu_IROS2017.pdf",
  code:"", badge:"Closest precedent",
  platforms:"1 UAV (DJI F330) + 3 ground robots (Duckiebots)",
  simulator:"Custom simulation",
  hardware:"Partial — sites and victims are projected; pickup is simulated",
  rl:"Yes",
  learned:"Finite-state controllers: each robot keeps a small internal memory state that selects its next macro-action and transitions on observations. Trained by iterative sampling-based expectation maximization (iSEM).",
  supplied:"The macro-action controllers themselves; the UAV and ground robots have different macro-action sets.",
  summary:"A search-and-rescue setting: one UAV surveys sites while three ground robots find and transport victims. Victim health deteriorates over time, and communication is limited and unreliable. This paper already combines all four properties the proposed project needs — heterogeneous robots, partial observability, asynchronous skills, and policy learning.",
  why:"The canonical precedent for a drone acquiring information that changes ground-robot decisions — exactly the mechanic at the heart of the proposed problem.",
  caveats:["Hardware experiments use a projection system: sites and victims are virtual and victim pickup is simulated. It demonstrates coordination, not physical grasping."],
  reading:"Read the domain description and the FSC representation before the iSEM derivation.",
  figures:[{
    src:"A11_domain.png", label:"Figure 3 — Hardware domain with 1 UAV and 3 UGVs",
    caption:"Overview of hardware domain with 1 UAV and 3 UGVs. A projection system visualises sites and victim locations/health. Victims are squares whose colour encodes health (green: high, yellow: low, red: expired).",
    explain:"Read the four panels as an <em>observation model</em>, not a photo series. Panels (a)–(b) show a ground robot close to a site: it sees the victim square directly and its colour, so health is fully observed locally. Panel (c) shows the same site where the victim's outer ring is black — the ground robot can tell there are no further victims there. Panel (d) is the crucial one: the UAV, flying high, <em>cannot carry anything</em> and only ever gets the outer-ring indicator — a coarse cue about whether a site is worth visiting. So the drone's value is purely informational, and the projection system is how the authors made that asymmetry concrete without building real sensing. This is the same design decision you face when deciding what the Crazyflie may and may not observe."
  }]
},
{
  id:"A12", tier:"A", thread:"options", relevance:5, order:1,
  title:"Between MDPs and semi-MDPs: A Framework for Temporal Abstraction in Reinforcement Learning",
  authors:"Richard S. Sutton, Doina Precup, Satinder Singh",
  year:1999, venue:"Artificial Intelligence 112",
  het:"no", hetKind:"none", appKey:"theory", methodKey:"theory", hetNote:"Single-agent framework; the heterogeneity comes later, from how you use it.",
  cite:"Sutton, Precup & Singh, AIJ 1999", bibkey:"sutton1999between",
  gist:"Defines an option as (initiation set, internal policy, termination) and the SMDP machinery for actions of variable duration.",
  useFor:"Cite whenever you introduce your skill abstraction, and specifically for the claim that options may be supplied rather than discovered.",
  url:"https://www-anw.cs.umass.edu/~barto/courses/cs687/Sutton-Precup-Singh-AIJ99.pdf",
  pdf:"A12_Options_SuttonPrecupSingh_AIJ1999.pdf", code:"", badge:"Foundational",
  platforms:"N/A (four-room gridworld)", simulator:"N/A", hardware:"No", rl:"Yes (framework)",
  learned:"Nothing, by itself — it defines the option and supplies learning/planning methods that account for variable durations.",
  supplied:"The option set, in the standard usage.",
  summary:"Defines an option as the triple <code>o = (I<sub>o</sub>, π<sub>o</sub>, β<sub>o</sub>)</code>: the states where it may start, the policy it runs internally, and its termination rule. A high-level policy picks the option; the internal controller then runs for many timesteps.",
  why:"This is the vocabulary for everything else. The single most important takeaway for a planning-oriented project: <strong>using options does not require discovering subtasks automatically</strong> — you may supply every option and learn only their selection.",
  caveats:[],
  reading:"Sections 2–3 give you the definition and the SMDP view; the four-room example makes it concrete.",
  optionTable:[
    ["I<sub>o</sub>","States where the option may start","LoCoBot is near an object, gripper empty"],
    ["π<sub>o</sub>","Policy executed inside the option","Approach → align → close gripper → lift"],
    ["β<sub>o</sub>","Termination rule / probability","Object secured, or grasp attempt failed"]
  ],
  figures:[{
    src:"A12_smdp.png", label:"Figure 1 — MDP, SMDP and options over an MDP",
    caption:"The state trajectory of an MDP is made up of small, discrete-time transitions, whereas that of an SMDP comprises larger, continuous-time transitions. Options enable an MDP trajectory to be analysed in either way.",
    explain:"Three trajectories of the same system, stacked, with time running left to right and state vertically. <strong>Top (MDP):</strong> a dense chain of filled dots — one decision per primitive timestep. <strong>Middle (SMDP):</strong> only a few open circles, far apart — decisions happen at irregular, widely separated moments, and the smooth curve between them is time you do not choose during. <strong>Bottom (Options over MDP):</strong> both are drawn at once — the fine dots are still there, but open circles mark where an option begins and ends. That third row is the entire design of your planner: the LoCoBot's grasp still consists of hundreds of controller steps, but your policy only wakes up at the circles. It also shows why durations must be modelled explicitly — the gaps between circles are visibly unequal, which is precisely the asynchrony that A10 and A11 have to handle."
  }]
},
{
  id:"A13", tier:"A", thread:"options", relevance:3, order:18,
  title:"The Option-Critic Architecture",
  authors:"Pierre-Luc Bacon, Jean Harb, Doina Precup",
  year:2017, venue:"AAAI 2017",
  het:"no", hetKind:"none", appKey:"theory", methodKey:"theory", hetNote:"Single-agent option discovery.",
  cite:"Bacon, Harb & Precup, AAAI 2017", bibkey:"bacon2017optioncritic",
  gist:"Learns intra-option policies and termination functions end-to-end from task reward, alongside option selection.",
  useFor:"Cite to explain what you deliberately do not do — and why engineered, interpretable skills are the right call for a planning contribution.",
  url:"https://arxiv.org/abs/1609.05140", pdf:"A13_OptionCritic_Bacon_AAAI2017.pdf", code:"", badge:"",
  platforms:"N/A (navigation, Pinball, Atari)", simulator:"N/A", hardware:"No", rl:"Yes",
  learned:"Internal option policies <em>and</em> termination functions, from task reward, jointly with option selection.",
  supplied:"The number of options; their initiation sets (all options available everywhere).",
  summary:"Extends the options framework so that the skills themselves are learned end-to-end from task reward, rather than supplied.",
  why:"Read it to understand what you are deliberately <em>not</em> doing. If you supply <code>pick</code>, <code>inspect</code> and <code>load</code> as engineered skills, you keep interpretability; option-critic trades that away.",
  caveats:["The number of options is chosen by the experimenter.","All options are available in every state.","Learned options need not correspond to interpretable skills such as “pick” or “inspect”."],
  reading:"Figure 1 plus the intra-option policy gradient theorem is enough for orientation.",
  figures:[{
    src:"A13_architecture.png", label:"Figure 1 — The option-critic architecture",
    caption:"Diagram of the option-critic architecture. The option execution model is depicted by a switch ⊥ over the contacts.",
    explain:"Follow the loop from the bottom. <strong>Environment</strong> emits state <code>s<sub>t</sub></code> (left) and reward <code>r<sub>t</sub></code> (upward arrow). The <strong>Critic</strong> box <code>Q<sub>U</sub>, A<sub>Ω</sub></code> consumes those and produces a TD error (the small self-loop). Above it sit the two learned pieces: <strong>Options</strong> <code>π<sub>ω</sub>, β<sub>ω</sub></code> — the intra-option policy and its termination — and above that the <strong>Policy over options</strong> <code>π<sub>Ω</sub></code>. The detail that repays attention is the <em>switch</em> drawn on the right: it is open while an option runs and closes only when <code>β<sub>ω</sub></code> fires, at which point <code>π<sub>Ω</sub></code> is consulted for a new <code>ω<sub>t</sub></code>. The action <code>a<sub>t</sub></code> leaves from the option level, never from <code>π<sub>Ω</sub></code> directly. Compare with A12's bottom row: the switch <em>is</em> the open circle. The arrows labelled <strong>Gradients</strong> running from the critic up into the options box are what this paper adds — in your setting those would be cut, because your options are engineered."
  }]
},
{
  id:"A15", tier:"A", thread:"async", relevance:5, order:11,
  title:"Modeling and Planning with Macro-Actions in Decentralized POMDPs",
  authors:"Christopher Amato, George Konidaris, Leslie P. Kaelbling, Jonathan P. How",
  year:2019, venue:"JAIR 64",
  het:"yes", hetKind:"capability", appKey:"logistics", methodKey:"none", hetNote:"Formalism is heterogeneity-capable; the warehouse domain mixes robot types but coalition size is the main constraint.",
  cite:"Amato et al., JAIR 2019", bibkey:"amato2019modeling",
  gist:"Formalises MacDec-POMDPs: planning over supplied skills under partial observability when skills terminate at different times.",
  useFor:"Cite as the formal specification your learned planner approximates, and for the unknown-versus-false distinction in the belief.",
  url:"https://doi.org/10.1613/jair.1.11418", pdf:"A15_MacDecPOMDP_Amato_JAIR2019.pdf", code:"", badge:"Theory",
  platforms:"Multi-robot warehouse", simulator:"N/A", hardware:"Yes (warehouse demo)", rl:"No — planning",
  learned:"Nothing. This is the planning formalism.",
  supplied:"The macro-action set, observation model and transition model.",
  summary:"Formalises <strong>MacDec-POMDPs</strong>: planning over supplied robot skills when agents have partial information and their skills terminate at different times. This is the theory underneath the asynchronous learning work.",
  why:"If you want your learned planner to have a principled specification rather than just an implementation, this is the object you are approximating. It also gives you the vocabulary for stating what is unknown versus false.",
  caveats:["Planning, not learning — expect exact/approximate solvers rather than gradient methods."],
  reading:"Sections 2–4 for the model; skim the dynamic-programming solvers.",
  figures:[{
    src:"A15_warehouse.png", label:"Figure 3 — The multi-robot warehouse domain",
    caption:"A multi-robot warehouse domain. A team of robots must find and retrieve boxes, some of which require two robots to move.",
    explain:"A physical tabletop warehouse: white walls forming corridors and two depot areas, scattered wooden boxes, and three visibly different robots (a green one, a white one and a blue one). The layout is doing the formal work. The corridors mean a robot's navigation macro-action takes a duration that depends on where it started — so the robots' skills terminate at different times by construction. The walls mean a robot cannot see the far side of the arena, so box locations are genuinely unknown rather than merely unmodelled. And because some boxes require two robots, there is a rendezvous constraint that only bites if both arrive — the same structure as your LoCoBot/TurtleBot load-unload dependency. This picture is the minimal physical setup that forces all three MacDec-POMDP ingredients at once, which is a useful template when you size your own four-room lab."
  }]
},
{
  id:"A16", tier:"A", thread:"simreal", relevance:5, order:4,
  title:"Spatial Intention Maps for Multi-Agent Mobile Manipulation",
  authors:"Jimmy Wu, Xingyuan Sun, Andy Zeng, Shuran Song, Szymon Rusinkiewicz, Thomas Funkhouser",
  year:2021, venue:"ICRA 2021",
  het:"yes", hetKind:"capability", appKey:"transport", methodKey:"valuerl",
  cite:"Wu et al., ICRA 2021", bibkey:"wu2021spatial",
  gist:"Double-DQN over spatial action maps; robots broadcast intended paths painted into a teammate's observation. Lift/push/throw robots, PyBullet to real with no fine-tuning.",
  useFor:"Cite as the strongest heterogeneous-capability RL result with physical manipulation, and to justify a controlled-perception setup as legitimate.",
  url:"https://spatial-intention-maps.cs.princeton.edu/", pdf:"A16_SpatialIntentionMaps_Wu_ICRA2021.pdf",
  code:"https://spatial-intention-maps.cs.princeton.edu/", badge:"Best RL + hardware match",
  platforms:"Anki Vector robots with lifting, pushing and throwing attachments",
  simulator:"PyBullet",
  hardware:"Yes — deployed without fine-tuning",
  rl:"Yes",
  learned:"A Double-DQN policy over spatial action maps: where to move, and whether to execute the robot's available manipulation action.",
  supplied:"Low-level motion execution; the attachment hardware defines each robot's single special ability.",
  summary:"A team of robots must move objects into a collection area. Different robots can lift, push, or throw, so complementary capabilities must be exploited. Each robot broadcasts its intended path, and teammates encode that intention spatially in their own observation.",
  why:"The strongest single match for heterogeneous capabilities + RL + physical manipulation, and the policies transfer to hardware with no fine-tuning. The controlled perception setup is directly analogous to your virtual-observation assumption.",
  caveats:["Hardware experiments use external fiducial tracking and a mirrored simulation to construct observations — perception is deliberately controlled, not solved.","Objects are simple cubes; manipulation is attachment-based rather than dexterous."],
  reading:"Section III (method) then the emergent-behaviour figures. Then clone the repo.",
  figures:[
  {
    src:"A16_overview.png", label:"Figure 2 — System overview",
    caption:"Overview. The system uses decentralized, asynchronous execution with communicating agents. Robot 1 is currently choosing a new action; it receives the intentions of the other agents, represented as path waypoints.",
    explain:"Read it left to right as one robot's decision. On the far left, the arena: four robots and a red receptacle, with the dashed callout marking the robot that is about to act. <strong>Communication</strong> (next column): robots 2, 3 and 4 each send a simple <code>(x, y)</code> — their intended waypoint, colour-coded red/blue/green. <strong>State representation</strong> is the key idea: those intentions are not appended as a vector but <em>painted into a map</em> — the “spatial intention map” panel — which is stacked with the robot's own overhead map (where the acting robot is circled in red). Both are images in the same frame. That stack feeds a <strong>fully convolutional Q-network</strong>, which outputs a <strong>Q-value map</strong> — one value per location — and the action is simply the arg-max pixel, shown selected on the right. Because intentions live in the same coordinate frame as the state, a convolution can directly learn “do not go where my teammate is already heading.” That is what makes the division of labour in their results emerge rather than be scripted."
  },
  {
    src:"A16_robots.png", label:"Figure 3 — Three robot types, three abilities",
    caption:"We experiment with multiple robot types, each with a unique ability.",
    explain:"Three photographs of the same Anki Vector base with three different attachments, labelled <strong>Lifting</strong>, <strong>Pushing</strong> and <strong>Throwing</strong> — and the red arrows show what each one does to a cube: lift carries it, push shoves it along the floor, throw launches it at range. This is heterogeneity reduced to its cheapest possible form. The bases, sensing and controllers are identical; only the end-effector differs, so any specialisation the policy learns must come from the capability difference and nothing else. It is a good template for your own ablations: if you want to claim the planner exploits the PX100's arm specifically, you want a variant of the team where that is the <em>only</em> thing that changed."
  }]
},
{
  id:"A09", tier:"A", thread:"aerial", relevance:5, order:5,
  title:"Hierarchical Language Models for Semantic Navigation and Manipulation in an Aerial-Ground Robotic System",
  authors:"Haokun Liu, Zhaoqi Ma, Yunong Li, Junichiro Sugihara, Yicheng Chen, Jinjie Li, Moju Zhao",
  year:2025, venue:"arXiv preprint",
  het:"yes", hetKind:"physical", appKey:"assembly", methodKey:"finetune",
  cite:"Liu et al., 2025", bibkey:"liu2025hierarchical",
  gist:"Drone gives overhead perception to a VLM; an LLM sequences preprogrammed ground-robot functions to rearrange letter blocks. Gazebo plus real lab.",
  useFor:"Cite as the closest Gazebo + hardware aerial-ground system, and as evidence that the integration is feasible — while noting the planner is not learned.",
  url:"https://arxiv.org/abs/2506.05020", pdf:"A09_AerialGround_HierLLM_Liu_2025.pdf", code:"", badge:"Gazebo + hardware",
  platforms:"Custom quadrotor + Unitree Go1 with a magnetic gripper",
  simulator:"Gazebo",
  hardware:"Yes — Gazebo workspace and a physical laboratory",
  rl:"No",
  learned:"A fine-tuned vision-language model for object identity and position from aerial images (their “GridMask” overlays a coordinate grid to improve spatial localisation).",
  supplied:"Motion planners and preprogrammed attach/detach functions; the LLM selects among them.",
  summary:"An aerial robot provides overhead perception that guides a ground robot to rearrange objects — for example, arranging letter blocks into a requested word while respecting constraints on which blocks may move.",
  why:"The clearest exact match for your simulator and embodiment: a heterogeneous aerial–ground planning architecture turned into a working Gazebo-and-hardware system. Treat it as the integration template, not the algorithm.",
  caveats:["The task planner is <strong>not</strong> trained with RL — it is a prompted LLM over supplied functions.","Manipulation is magnetic attachment, not general arm grasping."],
  reading:"Figures 1–2 and the experimental setup section give you most of the systems value.",
  figures:[
  {
    src:"A09_framework.png", label:"Figure 1 — Framework overview",
    caption:"Overview of the proposed hierarchical language model framework integrated into an aerial-ground robotic system. In the sub-task “move to (XX, XX)”, the aerial robot follows an optimized global path while continuously capturing bird-view images.",
    explain:"Three panels, and the split between them is the architecture. <strong>Left — reasoning:</strong> a human says “I want the dog to move to (XX, XX)”; that goes into <em>High-level Reasoning</em> (the brain icon), which emits a numbered decomposition — ① drone map construction, ② drone-and-dog cooperation. <strong>Middle — execution:</strong> a 3-D plot of the actual workspace showing two separate trajectories, the drone's in red from <em>Start</em> to <em>End</em> and the ground robot's in green, with a <em>Local BirdView</em> inset and a <em>Vel control</em> / <em>Vel vector generation</em> loop underneath. <strong>Right — reality:</strong> photographs of the quadrotor above and the Unitree Go1 below, both tracking the yellow dashed path among lettered blocks. The thing to take from it is the division of labour in the middle panel: the drone's path is planned to <em>keep the ground robot observed</em>, and the bird-view inset is the only place the ground robot's world model comes from. The LLM never touches velocities — that stays in the conventional control loop."
  },
  {
    src:"A09_workflow.png", label:"Figure 2 — Long-horizon task workflow",
    caption:"An overview of the workflow for a long-horizon task using the hierarchical MA-LLM framework. The task starts with the instruction: “Assemble the word OK, but do not move K.”",
    explain:"Four labelled bands, and following them top to bottom shows exactly where each kind of reasoning lives. The <strong>Reasoning Layer</strong> (green, top-left) takes the constrained instruction — assemble “OK”, <em>but do not move K</em> — and the LLM emits a <strong>Tasks List</strong>: an ordered set of “move Robot dog to…”, “pick up block O” steps. To its right the <strong>Perceptual Layer</strong> (blue) runs a VLM over bird-view drone frames and returns <em>Task-Specified Semantic Environment Information</em> — the JSON panel on the far right, with entries like <code>{\"name\": \"Robot_Dog\", \"coordinates\": {...}}</code> and <code>{\"name\": \"Block_O\", ...}</code>. Note what that JSON is: a symbolic state, produced by perception, in exactly the form the planner needs. The <strong>Execution Layer</strong> then expands each task into an <em>Executing Motion Functions List</em> and hands it to a conventional <strong>Motion Planner</strong>, with the filmstrip at the bottom showing the resulting motion. The negative constraint (“do not move K”) is honoured purely in the top band — it never becomes a controller constraint. That is the architectural tell: this system is strong at decomposition and weak at anything requiring a learned trade-off, which is precisely the gap your project targets."
  }]
},
{
  id:"A03", tier:"A", thread:"alloc", relevance:5, order:6,
  title:"Heterogeneous Multi-Robot Task Allocation and Scheduling via Reinforcement Learning",
  authors:"Dai et al.",
  year:2025, venue:"IEEE RA-L 2025",
  het:"yes", hetKind:"capability", appKey:"sar", methodKey:"attn",
  cite:"Dai et al., RA-L 2025", bibkey:"dai2025heteromrta",
  gist:"Attention policy trained with REINFORCE picks each robot's next task; coalitions emerge from synchronised arrival. Abstract 2D domains.",
  useFor:"Your primary RL allocation baseline. Also cite for the synchronised-arrival coalition constraint, and note that it defers task precedence.",
  url:"https://www.marmotlab.org/publications/73-RAL2025-HetMRTA.pdf", pdf:"A03_HeteroMRTA_Dai_RAL2025.pdf",
  code:"https://github.com/marmotlab/HeteroMRTA", badge:"Primary RL baseline",
  platforms:"Abstract robots with trait/skill vectors", simulator:"Abstract 2D scheduling", hardware:"No", rl:"Yes",
  learned:"Which robot goes to which task next, including coalition formation — a shared attention network trained with REINFORCE.",
  supplied:"Task requirements, robot skills, durations, positions. No perception, grasping or low-level control.",
  summary:"Robots carry skill vectors; tasks carry required-skill vectors, positions and durations. A task begins only once a sufficient coalition has <em>arrived</em>, and its robots are held there during execution. The terminal reward penalises total mission duration and redundant capabilities within a coalition.",
  why:"Your most direct RL allocation baseline, and the code is public. Also the cleanest statement of the synchronised-arrival constraint that your load/unload rendezvous shares.",
  caveats:["Experiments are abstract 2D scheduling problems.","Explicit task precedence is left to future work — but see SADCHER (A04) before claiming it."],
  reading:"Section IV (network) and the reward definition; then run the repo.",
  figures:[
  {
    src:"A03_scenario.png", label:"Figure 1 — Cooperative search and rescue",
    caption:"Cooperative search and rescue in various environments. Vectors represent robots' abilities and rescue tasks' requirements, with each element corresponding to a capability.",
    explain:"An isometric illustration of a disaster site — buildings, trees, a river — with drones, a removal truck and a rescue robot placed around it, and two line styles distinguishing <em>current plan</em> from <em>future plan</em>. The legend at top right is where the formalism hides: “agent abilities or task requirements” is drawn as a row of coloured chips, and each site is annotated with ticks and crosses against those chips. That is the whole trait model in one picture — a task is not “rescue”, it is a <em>requirement vector</em>, and a coalition is admissible only when the element-wise union of its members' ability vectors covers it. The crosses are the point: no single robot covers a site, so coalitions are forced rather than optional. When you define the PX100/TurtleBot/Crazyflie capability vectors, this is the representation you are adopting."
  },
  {
    src:"A03_network.png", label:"Figure 2 — Encoder–decoder policy network",
    caption:"Network structure used in this work. It follows an encoder-decoder structure where the status of agents and tasks such as trait vectors and trait requirements are first processed by agent, task and cross encoders.",
    explain:"Left to right in four stages. <strong>Inputs (far left):</strong> two graphs — an <em>Agent Graph</em> whose nodes carry capability vectors like <code>c<sub>a1</sub> = [0,0,1]</code>, and a <em>Task Graph</em> whose nodes carry requirement vectors like <code>q<sub>m2</sub> = [1,1,1]</code>, with a <em>species depot</em> node and one task already marked <em>finished by a<sub>1</sub></em>. <strong>Encoder (green/purple):</strong> separate Agent and Task encoders, then — and this is the part to notice — two <em>cross</em> encoders, Agent-Task and Task-Agent, drawn with crossing arrows. Robots are embedded in terms of the tasks they could serve and vice versa, so a capability is only ever represented relative to a demand. Those collapse into an <em>Agent Glimpse</em> and a <em>Task Glimpse</em>. <strong>Decoder:</strong> the current agent's state is fused with both glimpses into <code>ĥ</code>, and a <strong>Policy Layer</strong> emits attention values over candidate destinations — here <code>[0.0, 0.0, 0.2, 0.5, …]</code> across <em>depot, m<sub>1</sub>, m<sub>2</sub>, …</em>. <strong>Output (far right):</strong> one assignment, <code>a<sub>1</sub> → q<sub>m4</sub></code>. So the network chooses a <em>single next destination for a single robot</em>; coalitions are an emergent consequence of several robots being sent to the same task, never an explicit output. That is worth knowing before you use it as a baseline."
  }]
},
{
  id:"A04", tier:"A", thread:"alloc", relevance:4, order:7,
  title:"SADCHER: Scheduling using Attention-based Dynamic Coalitions of Heterogeneous Robots in Real-Time",
  authors:"Jakob Bichler, Andreu Matoses Gimenez, Javier Alonso-Mora",
  year:2025, venue:"MRS 2025",
  het:"yes", hetKind:"capability", appKey:"alloc", methodKey:"imitation",
  cite:"Bichler et al., MRS 2025", bibkey:"bichler2025sadcher",
  gist:"Imitation-learned scheduler with capabilities, dynamic coalitions and task precedence, via a dense robot×task reward matrix plus bipartite matching.",
  useFor:"Cite in related work to concede precedence in learned heterogeneous allocation already exists. Blocks any novelty claim on that combination.",
  url:"https://arxiv.org/abs/2510.14851", pdf:"A04_SADCHER_Bichler_MRS2025.pdf", code:"", badge:"Positioning",
  platforms:"Abstract heterogeneous robots", simulator:"Abstract", hardware:"No", rl:"No — imitation learning",
  learned:"A scheduling policy handling capabilities, dynamic coalitions <em>and task precedence</em>, trained by imitation from an optimal solver.",
  supplied:"Task graph, capability model, precedence constraints.",
  summary:"Learned real-time scheduling for heterogeneous teams where coalitions form and dissolve dynamically and tasks have precedence relations.",
  why:"<strong>Read this for positioning, not as a baseline.</strong> It is the clearest evidence that adding precedence to learned heterogeneous allocation is already studied — so that combination cannot be your novelty claim.",
  caveats:["Imitation learning against a solver, so performance is bounded by the expert.","Abstract task model; no physical execution."],
  reading:"Figure 2 and the problem formulation.",
  figures:[{
    src:"A04_architecture.png", label:"Figure 2 — Sadcher architecture",
    caption:"Sadcher architecture overview. Robot and task graphs are processed by graph attention and transformer encoders and concatenated with distance features. The reward matrix is estimated by the Idle and Reward MLPs and final task assignments follow from relaxed bipartite matching.",
    explain:"Two symmetric input streams that meet in the middle. <strong>Top (blue):</strong> robot features <code>r<sub>i</sub> = [p<sup>r</sup><sub>i</sub>, t<sup>r</sup><sub>i</sub>, a<sup>r</sup><sub>i</sub>, c<sup>r</sup><sub>i</sub>]</code> — position, time, availability, capability — through <code>GAT<sub>R</sub></code> then <code>Transformer<sub>R</sub></code>, producing a <code>(B, N, d)</code> embedding. <strong>Bottom (red):</strong> task features <code>t<sub>j</sub> = [p<sup>t</sup><sub>j</sub>, t<sup>t</sup><sub>j</sub>, r<sup>t</sup><sub>j</sub>, s<sup>t</sup><sub>j</sub>]</code> through the mirrored <code>GAT<sub>T</sub></code> / <code>Transformer<sub>T</sub></code> stack. They meet at <strong>Expand + Concat</strong>, which forms the full robot×task grid <code>(B, N, M, 4d+1)</code> — every pairing scored jointly — with a small green <strong>Distance MLP</strong> injecting travel cost as the “+1”. Two heads then read that grid: an <strong>Idle MLP</strong> producing an <code>(B, N, 1)</code> should-this-robot-wait signal, and a <strong>Reward MLP</strong> producing the <code>(B, N, M)</code> reward matrix drawn as a heatmap. Finally <strong>Relaxed Bipartite Matching</strong> turns that matrix into <strong>Assignments</strong>. The architectural lesson for you: because the output is a dense robot×task reward matrix rather than a sequential choice, coalitions and precedence can be expressed as constraints on the matching step — compare that with HeteroMRTA's one-robot-at-a-time decoder."
  }]
},
{
  id:"A01", tier:"A", thread:"alloc", relevance:4, order:8,
  title:"An Interleaved Approach to Trait-Based Task Allocation and Scheduling",
  authors:"Glen Neville, Andrew Messing, Harish Ravichandar, Seth Hutchinson, Sonia Chernova",
  year:2021, venue:"IROS 2021",
  het:"yes", hetKind:"capability", appKey:"alloc", methodKey:"none",
  cite:"Neville et al., IROS 2021", bibkey:"neville2021itags",
  gist:"Interleaves trait-based allocation, scheduling and motion planning in one search instead of a pipeline.",
  useFor:"Cite when arguing that allocation, scheduling and motion feasibility cannot be decided independently — the motivation for a single coupled planner.",
  url:"https://arxiv.org/abs/2108.02773", pdf:"A01_ITAGS_Neville_IROS2021.pdf", code:"", badge:"",
  platforms:"Generic heterogeneous teams", simulator:"Abstract", hardware:"No", rl:"No — heuristic search",
  learned:"Nothing. Heuristic search over allocations.",
  supplied:"Trait requirements, scheduling constraints, motion constraints.",
  summary:"ITAGS interleaves capability-based allocation, scheduling <em>and motion planning</em> in a single search, rather than solving them in sequence.",
  why:"The planning-side foundation for your problem: it is the clearest statement of why who-acts, when, and along-which-route cannot be decided independently. Your learned value function would be guiding a search of essentially this shape.",
  caveats:["No learning; heuristic weights are hand-tuned (their α study)."],
  reading:"Figures 1–2 and the heuristic definitions.",
  figures:[
  {
    src:"A01_architecture.png", label:"Figure 1 — Hierarchical framework",
    caption:"High-level architecture of the hierarchical framework.",
    explain:"Three stacked stages with feedback, and the feedback is the contribution. A grey <strong>Specification</strong> box feeds three things down the left as dashed arrows: <em>trait requirements</em> into <strong>Incremental task allocation</strong> (blue, containing Heuristic 1 and Heuristic 2), <em>scheduling constraints</em> into <strong>Scheduling</strong> (orange), and <em>motion constraints</em> into <strong>Motion planning</strong> (green). Each stage emits a result to the right — <em>Full allocation</em>, <em>Full schedule</em>, <em>Motion plans</em>. Now read the arrows going the other way: <em>current allocation</em> flows down to scheduling, <em>current schedule</em> down to motion planning, and critically <em>feasibility &amp; duration</em> flows back up from motion planning to scheduling, and <em>feasibility &amp; schedule</em> flows back up to allocation. That upward path is why this is “interleaved” rather than a pipeline — a partial allocation is scored by what the motion planner says it would actually cost. In your project, that returned cost is exactly the quantity you would replace with a learned estimate."
  },
  {
    src:"A01_itag_graph.png", label:"Figure 2 — Incremental task allocation graph",
    caption:"An example incremental task allocation graph, alongside Algorithm 1 (ITAGS).",
    explain:"On the left, a search tree whose nodes are <em>partial</em> allocations, expanding left to right; on the right, the accompanying allocation matrix showing agents as rows and tasks as columns with 0/1 entries, and the ITAGS pseudocode. The important detail is that the root is the <em>empty</em> allocation and each edge commits one more agent-to-task assignment, so a node is a partially specified team plan, not a complete one. The pseudocode then pops the lowest-value node from a priority queue and expands successors — plain best-first search where the heuristic must score an incomplete allocation. That is the hook for learning: a partial allocation is precisely the object your value function would have to evaluate, and it is also where the “is this inspection worth it?” question would be answered."
  }]
},
{
  id:"A05", tier:"A", thread:"alloc", relevance:4, order:9,
  title:"Learning and Optimizing the Efficacy of Spatio-Temporal Task Allocation under Temporal and Resource Constraints",
  authors:"Jiazhen Liu, Glen Neville, Jinwoo Park, Sonia Chernova, Harish Ravichandar",
  year:2026, venue:"arXiv preprint",
  het:"yes", hetKind:"capability", appKey:"alloc", methodKey:"model",
  cite:"Liu et al., 2026", bibkey:"liu2026eitags",
  gist:"Learns how coalition composition affects task efficacy and uses it inside interleaved allocation/scheduling/path planning. Extends Q-ITAGS.",
  useFor:"The closest prior instance of a learned component embedded in a symbolic planner — cite as the template your approach extends.",
  url:"https://arxiv.org/abs/2601.02505", pdf:"A05_E-ITAGS_Liu_2026.pdf", code:"", badge:"",
  platforms:"Generic heterogeneous teams", simulator:"Abstract", hardware:"No", rl:"Partly — learned efficacy model",
  learned:"How a coalition's capabilities affect task <em>efficacy</em>, learned and then used inside the planner.",
  supplied:"The allocation/scheduling/path-planning machinery from ITAGS.",
  summary:"E-ITAGS extends Q-ITAGS (ISRR 2024), learning the mapping from coalition composition to task performance while still interleaving allocation, scheduling and path planning.",
  why:"The closest existing instance of the pattern you want — a learned component <em>inside</em> a symbolic planner rather than replacing it. Read it to see how they keep the planner's guarantees around the learned part.",
  caveats:["Abstract domains; the learned quantity is task efficacy, not the value of information."],
  reading:"Compare directly against A01 to isolate what the learning adds.",
  figures:[]
},
{
  id:"A02", tier:"A", thread:"alloc", relevance:4, order:10,
  title:"Learning Task Requirements and Agent Capabilities for Multi-agent Task Allocation",
  authors:"Bo Fu, William Smith, Denise Rizzo, Matthew Castanier, Maani Ghaffari, Kira Barton",
  year:2022, venue:"arXiv preprint",
  het:"yes", hetKind:"capability", appKey:"inspect", methodKey:"model",
  cite:"Fu et al., 2022", bibkey:"fu2022learning",
  gist:"Learns capability and task-requirement vectors from observed team performance, then feeds them to an optimisation-based allocator. ROS/Gazebo experiments.",
  useFor:"Cite when justifying where capability vectors come from, or for prior art on learning a model that a symbolic allocator consumes.",
  url:"https://arxiv.org/abs/2211.03286", pdf:"A02_LearnTraits_Fu_2022.pdf", code:"", badge:"Uses Gazebo",
  platforms:"Simulated ground robots", simulator:"ROS / Gazebo", hardware:"No", rl:"No — supervised + optimization",
  learned:"Capability and requirement constraints, inferred from observed team performance.",
  supplied:"The optimisation-based allocator that consumes them.",
  summary:"Rather than hand-specifying which capabilities a task needs, this learns those constraints from whether teams succeeded, then feeds them to an optimisation-based allocator. Evaluated on ROS/Gazebo exploration and manipulation tasks.",
  why:"One of the few papers in this set that actually runs in Gazebo, and it answers a question you will hit immediately: where do the capability vectors come from?",
  caveats:["The allocator is an optimiser, not a learned policy.","Task set is small."],
  reading:"Figure 1 and the learning formulation.",
  figures:[{
    src:"A02_architecture.png", label:"Figure 1 — System architecture",
    caption:"System architecture. The architecture comprises a simulation/experimental environment, a learning model that inputs team configurations and performances and learns agent capabilities and task requirements, and a task allocation model.",
    explain:"A left-to-right pipeline of three boxes, and the loop closes back on itself. <strong>Simulation / Experiment</strong> (left) runs a given team on a task and emits <em>team and performance pairs</em> — that is, a team composition plus whether it succeeded. <strong>Learning model</strong> (middle) consumes those pairs and fits a boundary, drawn as the curve over scattered points, yielding <em>agent capabilities and task requirements</em>. <strong>Task allocation model</strong> (right) takes those learned vectors and solves for <em>optimal routes, schedules and teams</em>. The direction of information flow is the whole idea: capability vectors are an <em>output</em> of experience here, not an input from the designer. Compare with A03, where the identical vectors are assumed given. If you are going to assert that a Crazyflie “can inspect” and a PX100 “can grasp ≤50 g”, this paper is the one that asks how you would ever calibrate those numbers honestly."
  }]
},
{
  id:"A06", tier:"A", thread:"arch", relevance:4, order:12,
  title:"Capability-Aware Shared Hypernetworks for Flexible Heterogeneous Multi-Robot Coordination",
  authors:"Bo Fu, Pratap Tokekar, Harish Ravichandar et al.",
  year:2025, venue:"CoRL 2025 (PMLR v305)",
  het:"yes", hetKind:"capability", appKey:"generalise", methodKey:"hyper",
  cite:"Fu et al., CoRL 2025", bibkey:"fu2025cash",
  gist:"A hypernetwork generates each robot's decoder weights from its capability vector, so one shared network covers unseen team compositions.",
  useFor:"Cite for the generalisation protocol: how to test transfer to held-out team compositions and capability values without retraining.",
  url:"https://proceedings.mlr.press/v305/fu25a.html", pdf:"A06_CASH_Fu_CoRL2025.pdf", code:"", badge:"",
  platforms:"Heterogeneous teams (incl. Robotarium)", simulator:"Simulation + Robotarium", hardware:"Yes (Robotarium)", rl:"Yes",
  learned:"Capability-conditioned policies: a hypernetwork generates each robot's decoder weights from its capability vector.",
  supplied:"The capability vectors themselves.",
  summary:"CASH sits between fully shared and fully individualised policy parameters: one shared network, but per-robot behaviour generated on the fly from capabilities. Evaluated on transfer to unseen team compositions and unseen capability values.",
  why:"This is the architecture to copy if you want the “does it generalise to a different team?” experiment — swapping the TurtleBot for a second LoCoBot, or changing payload limits, without retraining.",
  caveats:["Not a symbolic task planner — it conditions low-level policies.","Capability vectors are supplied, not learned (contrast A02)."],
  reading:"Figure 1, then the generalisation experiments.",
  figures:[{
    src:"A06_architecture.png", label:"Figure 1 — CASH between shared and individual policies",
    caption:"We introduce Capability-Aware Shared Hypernetworks (CASH) (middle), a novel class of soft parameter sharing architectures that establishes and spans the broad spectrum between shared (left) and individualized (right) parameter designs.",
    explain:"The figure is an argument laid out as a spectrum — read the coloured bar along the bottom first: <strong>Shared Policies</strong> at the left end, <strong>Indiv. Policies</strong> at the right, and CASH claimed in the middle. The <strong>left panel</strong> shows Robot 1…n all pointing at one identical grey network: cheap, but every robot behaves the same. The <strong>right panel</strong> shows Robot 1…n each owning a differently-coloured network: expressive, but parameters grow with team size and a new robot type has no policy at all. The <strong>middle panel</strong> is the mechanism. Two shared components — a <strong>Hyper Adapter</strong> (top) that takes <em>capabilities</em> (orange input nodes) and emits <em>decoder weights</em> (blue output nodes), and an <strong>RNN Encoder</strong> (bottom) that takes <em>observations</em> (pink) through GRU units. Their outputs meet at the <strong>Adaptive Decoder</strong>, drawn with dashed blue edges to signal that its weights were <em>generated, not stored</em> — the label “decentralized online generation” says it explicitly. One shared parameter set, yet Robot 1…N each receive a different effective network, because each supplied a different capability vector. That is why an unseen team composition needs no retraining: a new robot is just a new input to the Hyper Adapter."
  }]
},
{
  id:"A14", tier:"A", thread:"arch", relevance:3, order:13,
  title:"Heterogeneous Multi-Robot Reinforcement Learning",
  authors:"Matteo Bettini, Ajay Shankar, Amanda Prorok",
  year:2023, venue:"AAMAS 2023",
  het:"yes", hetKind:"physical", appKey:"navigation", methodKey:"ppognn",
  cite:"Bettini, Shankar & Prorok, AAMAS 2023", bibkey:"bettini2023heterogeneous",
  gist:"HetGPPO keeps per-robot policy parameters over a shared communication graph, producing behavioural specialisation. Two RoboMaster robots.",
  useFor:"Cite for the physical-vs-behavioural heterogeneity taxonomy, and as the individual-parameters end of the sharing spectrum against CASH.",
  url:"https://arxiv.org/abs/2301.07137", pdf:"A14_HetGPPO_Bettini_AAMAS2023.pdf", code:"", badge:"",
  platforms:"2 RoboMaster ground robots", simulator:"VMAS", hardware:"Yes", rl:"Yes",
  learned:"Differentiated low-level cooperative behaviour — PPO with per-robot policy parameters and graph-based inter-robot communication.",
  supplied:"Communication topology; reward shaping for progress and collision avoidance.",
  summary:"Two differently sized robots joined by a rigid bar must coordinate so the large one passes a large gap and the small one a small gap. HetGPPO keeps separate policy parameters per robot while sharing a communication graph.",
  why:"Read for the architecture and the taxonomy of physical versus behavioural heterogeneity. It is not a task planner.",
  caveats:["Does not learn a symbolic sequence such as inspect → retrieve → hand over → deliver.","Contribution is policy architecture and behavioural specialisation."],
  reading:"Figure 2 for the architecture; the taxonomy in Section 3 is genuinely useful vocabulary.",
  figures:[{
    src:"A14_architecture.png", label:"Figure 2 — GPPO vs HetGPPO",
    caption:"Architecture of GPPO and HetGPPO: MARL models with communicating agents. Each agent passes its observation through a network and exchanges messages with neighbours.",
    explain:"Two networks drawn side by side for direct comparison. <strong>Left (GPPO):</strong> every agent's observation <code>o<sub>i</sub></code> flows through GNN and decoder blocks that are <em>the same shade</em> — one shared parameter set, fanning out from a single node at the top labelled <em>Shared</em>. <strong>Right (HetGPPO):</strong> the identical graph topology, but each agent's blocks are <em>differently coloured</em> and the top node is labelled <em>Individual</em> — separate parameters per agent, while messages still pass between neighbours. The communication structure is deliberately held constant so the only variable is parameter sharing. Read it directly against CASH (A06): all three points on that spectrum are now in front of you — shared (GPPO), individual (HetGPPO), and generated-from-capabilities (CASH). HetGPPO buys behavioural specialisation at the cost of parameters that scale with the team and cannot absorb a robot type it never trained on."
  }]
},
{
  id:"A07", tier:"A", thread:"llm", relevance:3, order:14,
  title:"COHERENT: Collaboration of Heterogeneous Multi-Robot System with Large Language Models",
  authors:"Kehui Liu, Zixin Tang, Dong Wang, Zhigang Wang, Xuelong Li, Bin Zhao",
  year:2024, venue:"arXiv preprint (rev. 2025)",
  het:"yes", hetKind:"physical", appKey:"household", methodKey:"llm",
  cite:"Liu et al., 2024", bibkey:"liu2024coherent",
  gist:"A central LLM assigns subtasks to quadrotors, a robot dog and an arm; executors report failures as text that drives replanning. Ships a benchmark.",
  useFor:"Cite as the LLM alternative and its limit: no quantity is optimised, so it cannot weigh whether an inspection is worth its cost.",
  url:"https://arxiv.org/abs/2409.15146", pdf:"A07_COHERENT_Liu_2024.pdf",
  code:"https://github.com/MrKeee/COHERENT", badge:"Benchmark",
  platforms:"3 quadrotors + arm-equipped Unitree Aliengo + Franka Panda",
  simulator:"OmniGibson on Isaac Sim (BEHAVIOR-1K)", hardware:"Yes", rl:"No",
  learned:"Nothing — coordination is prompted LLMs plus execution feedback.",
  supplied:"Robot action libraries and feasibility rules.",
  summary:"A central LLM proposes and assigns subtasks across quadrotors, a robotic dog and a robotic arm; robot-specific executors select feasible actions, report outcomes, and that feedback revises the plan. Ships a heterogeneous collaboration benchmark.",
  why:"Useful for benchmark design and for how they handle execution failure and replanning across very different embodiments.",
  caveats:["Does not demonstrate learning a task policy and manipulation skills together through RL.","Action libraries and feasibility rules are supplied by hand."],
  reading:"Figure 2 (the PEFA loop) and the benchmark description.",
  figures:[{
    src:"A07_pefa.png", label:"Figure 2 — The PEFA mechanism",
    caption:"PEFA mechanism in COHERENT for heterogeneous multi-robot task planning. It consists of two stages, a task assigner and robot executors. The proposal module decomposes the human instruction into subgoals that can be assigned to individual robots.",
    explain:"A closed loop of four lettered stages — Proposal-Execution-Feedback-Adjustment — spanning two coloured regions: a <strong>Task Assigner</strong> (orange) and <strong>Robot Executors</strong> (blue), with a <em>Simulation</em> column on the right. <strong>(a) Proposal:</strong> the assigner LLM reads robot capabilities and observations and emits an <em>Initial Proposal</em> — a subgoal per robot, the assigned robot list shown beside it. <strong>(b) Execution:</strong> each robot's executor LLM turns its subgoal into an <em>Action List</em> and runs <em>Action Validation</em> against the simulator, branching <em>Success</em> or <em>Fail</em>. <strong>(c) Feedback:</strong> the outcome returns as structured text — <em>Failure Feedback</em> carrying <em>potential reasons</em>, or <em>Success Feedback</em>. <strong>(d) Adjustment:</strong> the assigner appends that to a <em>Dialogue History</em> and issues an <em>Updated Proposal</em>, and the loop repeats until done. What to take from it: the replanning signal is natural-language failure explanation accumulating in a context window, not a value estimate. That is a real strength — it recovers from unforeseen failures without a model — and a real limitation: nothing here can weigh whether a costly inspection is <em>worth</em> it, because there is no quantity being optimised. Your project targets exactly that missing quantity."
  }]
},
{
  id:"A08", tier:"A", thread:"llm", relevance:3, order:15,
  title:"EMOS: Embodiment-aware Heterogeneous Multi-robot Operating System with LLM Agents",
  authors:"Junting Chen, Checheng Yu, Xunzhe Zhou, Tianqi Xu, Yao Mu, Mengkang Hu, Wenqi Shao et al.",
  year:2024, venue:"arXiv preprint (rev. 2025)",
  het:"yes", hetKind:"physical", appKey:"household", methodKey:"llm",
  cite:"Chen et al., 2024", bibkey:"chen2024emos",
  gist:"LLM agents reason over robot embodiment to allocate subtasks; introduces the Habitat-MAS benchmark.",
  useFor:"Cite for benchmark design and for how to encode physically grounded capabilities in a planner-readable form.",
  url:"https://arxiv.org/abs/2410.22662", pdf:"A08_EMOS_Chen_2024.pdf", code:"", badge:"Benchmark",
  platforms:"Heterogeneous simulated robots", simulator:"Habitat", hardware:"No", rl:"No",
  learned:"Nothing — embodiment-aware LLM agents.",
  supplied:"Robot URDF/embodiment descriptions, action APIs.",
  summary:"Robots reason about their own embodiment (what their body can physically do) to decide who should take which subtask. Introduces the Habitat-MAS benchmark spanning perception, navigation and manipulation.",
  why:"Mainly a benchmark-design reference, plus a concrete answer to how you encode physically grounded capabilities in a way a planner can consume.",
  caveats:["LLM-driven; no learned policy.","Simulation only."],
  reading:"The Habitat-MAS task taxonomy.",
  figures:[]
},
{
  id:"A17", tier:"A", thread:"simreal", relevance:3, order:16,
  title:"Asymmetric Self-Play-Enabled Intelligent Heterogeneous Multirobot Catching System Using Deep Multiagent Reinforcement Learning",
  authors:"Yuan Gao et al.",
  year:2023, venue:"IEEE T-RO 2023",
  het:"yes", hetKind:"role", appKey:"pursuit", methodKey:"selfplay",
  cite:"Gao et al., T-RO 2023", bibkey:"gao2023asymmetric",
  gist:"Asymmetric self-play and curriculum learning coordinate ground pursuers, observer drones and communication relays. Unity to indoor/outdoor hardware.",
  useFor:"Cite for role-differentiated aerial-ground RL on hardware, and for credit assignment when roles contribute in different currencies.",
  url:"https://freeformrobotics.org/wp-content/uploads/2023/03/22-1012.pdf", pdf:"A17_AsymSelfPlayCatching_Gao_TRO2023.pdf",
  code:"", badge:"",
  platforms:"Ground pursuers + Tello observer drones + communication-relay robots",
  simulator:"Unity ML-Agents (simplified robot models)", hardware:"Yes — indoor and outdoor", rl:"Yes",
  learned:"Coordinated pursuit and positioning, via asymmetric self-play and curriculum learning.",
  supplied:"Conventional controllers execute the learned motion commands; positions come from external tracking.",
  summary:"A heterogeneous catching team — ground robots that pursue, drones that observe, and robots that maintain the communication link — must coordinate under observation and communication constraints.",
  why:"One of very few papers with genuinely role-differentiated aerial–ground RL deployed outdoors. The explicit communication-relay role is an unusual and instructive form of heterogeneity.",
  caveats:["Observations rely on externally tracked positions.","Studies coordinated pursuit, not manipulation."],
  reading:"Figure 4 for the system; the self-play curriculum in Section IV.",
  figures:[{
    src:"A17_system.png", label:"Figure 4 — Real-world system and training framework",
    caption:"Illustration of our real-world system and the training framework we used. The top left shows the scenario setup for the whole experiment, the bottom left the strategies for each corresponding team, and the middle the policy observation structure.",
    explain:"Three regions worth reading in order. <strong>Left:</strong> the physical setup — an arena schematic with the three robot roles broken out into separate policy blocks (<em>observer robots policy</em>, <em>catcher robots policy</em>, <em>communication robots policy</em>), and beneath them the <em>asymmetric self-play</em> block pitting the catching team against a target team. <strong>Middle — Policy observation:</strong> the inputs are split into a <em>Vector Observation</em> (position and velocity of teammates, position and velocity of the target) and a <em>Visual Observation</em> (a segmented image, shown as a coloured grid of the arena), which pass through separate encoders before merging. <strong>Right:</strong> the merged features run through the recurrent policy stack, and a <em>Group Reward Distribution</em> block combines an <em>External Reward</em> with per-agent terms. That reward block is the one to study: because the three roles contribute to a single team outcome in completely different currencies — a relay robot never catches anything — the credit assignment has to be explicit. You will face the identical issue the first time your Crazyflie's only contribution to mission time is an inspection that let the LoCoBot skip a room."
  }]
},

/* ─────────────────────────────  TIER B  ───────────────────────────── */
{ id:"B03", tier:"B", thread:"async", relevance:5, order:17,
  title:"Macro-Action-Based Multi-Agent/Robot Deep Reinforcement Learning under Partial Observability",
  authors:"Yuchen Xiao", year:2022, venue:"PhD thesis, Northeastern University",
  het:"yes", hetKind:"physical", appKey:"logistics", methodKey:"macroac",
  cite:"Xiao, PhD thesis 2022", bibkey:"xiao2022thesis",
  gist:"Consolidates the whole macro-action deep MARL programme with all domains and ablations in one place.",
  useFor:"Use as a handbook when a detail in A10 is compressed; rarely the right citation itself.",
  url:"https://arxiv.org/abs/2209.10003", pdf:"B03_MacroActionThesis_Xiao_2022.pdf", code:"", badge:"Best handbook",
  platforms:"Fetch, TurtleBots, warehouse", simulator:"Various", hardware:"Yes", rl:"Yes",
  learned:"The consolidated macro-action deep MARL line — value-based and actor–critic, centralized and decentralized.",
  supplied:"Macro-action controllers.",
  summary:"The single best consolidated treatment of the whole macro-action deep MARL programme, with all the domains and ablations in one place.",
  why:"Use it as a handbook rather than a paper — when a detail in A10 is compressed, it is expanded here.",
  caveats:[], reading:"Use the table of contents; do not read linearly.", figures:[] },

{ id:"B01", tier:"B", thread:"async", relevance:4, order:20,
  title:"Macro-Action-Based Deep Multi-Agent Reinforcement Learning",
  authors:"Yuchen Xiao, Joshua Hoffman, Christopher Amato", year:2020, venue:"CoRL 2019 / arXiv",
  het:"yes", hetKind:"physical", appKey:"logistics", methodKey:"valuerl",
  cite:"Xiao, Hoffman & Amato, 2020", bibkey:"xiao2020macro",
  gist:"Value-based deep MARL over macro-actions with asynchronous termination (Mac-DRQN family).",
  useFor:"Cite as the value-based counterpart to Mac-IAICC's actor-critic.",
  url:"https://arxiv.org/abs/2004.08646", pdf:"B01_MacroActionDeepMARL_Xiao_2020.pdf", code:"", badge:"",
  platforms:"Simulated + robot domains", simulator:"Abstract", hardware:"No", rl:"Yes",
  learned:"Mac-DRQN / Mac-CAC family of value-based macro-action methods.",
  supplied:"Macro-action controllers.",
  summary:"The direct predecessor of A10: value-based deep MARL over macro-actions with asynchronous termination.",
  why:"Read if you want the value-based comparison point to Mac-IAICC's actor–critic.",
  caveats:[], reading:"", figures:[] },

{ id:"B18", tier:"B", thread:"async", relevance:4, order:21,
  title:"Macro-Action-Based Deep Multi-Agent Reinforcement Learning (CoRL proceedings version)",
  authors:"Yuchen Xiao, Joshua Hoffman, Christopher Amato", year:2019, venue:"CoRL 2019 (PMLR v100)",
  het:"yes", hetKind:"physical", appKey:"logistics", methodKey:"valuerl",
  cite:"Xiao, Hoffman & Amato, CoRL 2019", bibkey:"xiao2019macro",
  gist:"Published proceedings version of the macro-action deep MARL work.",
  useFor:"Use this citation rather than the arXiv version.",
  url:"https://proceedings.mlr.press/v100/xiao20a.html", pdf:"B18_MacroActionDecPOMDP_Xiao_CoRL2019b.pdf", code:"", badge:"",
  platforms:"Warehouse tool delivery", simulator:"Abstract", hardware:"Yes", rl:"Yes",
  learned:"Macro-action deep MARL.", supplied:"Macro-action controllers.",
  summary:"The published proceedings version of B01 — cite this one.",
  why:"Citation hygiene.", caveats:[], reading:"", figures:[] },

{ id:"B02", tier:"B", thread:"async", relevance:4, order:22,
  title:"Learning Multi-Robot Decentralized Macro-Action-Based Policies via a Centralized Q-Net",
  authors:"Yuchen Xiao, Joshua Hoffman, Tian Xia, Christopher Amato", year:2019, venue:"arXiv / ICRA",
  het:"yes", hetKind:"physical", appKey:"logistics", methodKey:"valuerl",
  cite:"Xiao et al., 2019", bibkey:"xiao2019learning",
  gist:"Distils decentralised macro-action policies from a centralized Q-net.",
  useFor:"Cite for the centralized-training/decentralized-execution pattern at the macro-action level.",
  url:"https://arxiv.org/abs/1909.08776", pdf:"B02_CentralizedQnet_Xiao_CoRL2019.pdf", code:"", badge:"",
  platforms:"Warehouse robots", simulator:"Abstract", hardware:"Yes", rl:"Yes",
  learned:"Decentralized macro-action policies distilled from a centralized Q-net.",
  supplied:"Macro-action controllers.",
  summary:"Centralized training, decentralized execution, at the macro-action level.",
  why:"The CTDE pattern you would likely adopt if the planner must eventually run on-robot.",
  caveats:[], reading:"", figures:[] },

{ id:"B09", tier:"B", thread:"async", relevance:4, order:23,
  title:"Asynchronous Cooperative Multi-Agent Reinforcement Learning with Limited Communication",
  authors:"Sydney Dolan, Siddharth Nayak, Jasmine Jerry Aloor, Hamsa Balakrishnan", year:2025, venue:"arXiv",
  het:"no", hetKind:"none", appKey:"alloc", methodKey:"macroac", hetNote:"Agents are interchangeable; the contribution is asynchrony and communication limits.",
  cite:"Dolan et al., 2025", bibkey:"dolan2025asynchronous",
  gist:"Asynchronous cooperative MARL where agents cannot rely on constant communication.",
  useFor:"Cite if communication dropouts become part of the problem formulation.",
  url:"https://arxiv.org/abs/2502.00558", pdf:"B09_AsyncMARL_LimitedComm_Dolan_2025.pdf", code:"", badge:"",
  platforms:"Multi-agent", simulator:"Abstract", hardware:"No", rl:"Yes",
  learned:"Asynchronous cooperative policies under communication limits.",
  supplied:"Communication model.",
  summary:"Recent asynchronous MARL where agents cannot rely on constant communication.",
  why:"Relevant the moment Crazyflie link dropouts become part of your problem rather than an annoyance.",
  caveats:[], reading:"", figures:[] },

{ id:"B17", tier:"B", thread:"alloc", relevance:3, order:24,
  title:"ScheduleNet: Learn to Solve Multi-agent Scheduling Problems with Reinforcement Learning",
  authors:"Wang, Gombolay et al.", year:2020, venue:"RSS 2020 / Georgia Tech CORE Robotics",
  het:"yes", hetKind:"capability", appKey:"alloc", methodKey:"attn",
  cite:"Wang & Gombolay, RSS 2020", bibkey:"wang2020schedulenet",
  gist:"Graph-attention RL learns scheduling heuristics for multi-agent problems with temporal constraints.",
  useFor:"Cite as the canonical learned-scheduler predecessor that A03 and A04 are implicitly measured against.",
  url:"https://core-robotics.gatech.edu/wp-content/uploads/sites/958/2020/06/RSS20_ScheduleNet.pdf",
  pdf:"B17_ScheduleNet_Wang_RSS2020.pdf", code:"", badge:"",
  platforms:"Multi-agent scheduling", simulator:"Abstract", hardware:"No", rl:"Yes",
  learned:"Scheduling heuristics via graph attention and RL.",
  supplied:"Task graph with precedence and deadlines.",
  summary:"An early and frequently-cited learned scheduler for multi-agent problems with temporal constraints.",
  why:"The comparison point A03 and A04 are implicitly measured against.",
  caveats:[], reading:"", figures:[] },

{ id:"B07", tier:"B", thread:"alloc", relevance:3, order:25,
  title:"Heterogeneous Coalition Formation and Scheduling with Multi-Skilled Robots",
  authors:"Ashay Aswale, Carlo Pinciroli", year:2023, venue:"arXiv / RA-L",
  het:"yes", hetKind:"capability", appKey:"alloc", methodKey:"none",
  cite:"Aswale & Pinciroli, 2023", bibkey:"aswale2023heterogeneous",
  gist:"Optimisation for coalition formation and scheduling with multi-skilled robots; no learning.",
  useFor:"Cite as the classical optimisation baseline a learned allocator should be measured against.",
  url:"https://arxiv.org/abs/2306.11936", pdf:"B07_HetCoalitionScheduling_Aswale_2023.pdf", code:"", badge:"",
  platforms:"Multi-skilled robots", simulator:"Abstract", hardware:"No", rl:"No",
  learned:"Nothing — optimisation.", supplied:"Skill and task models.",
  summary:"Non-learning optimisation for coalition formation and scheduling with multi-skilled robots.",
  why:"The classical baseline your learned allocator should beat — or at least be compared against.",
  caveats:[], reading:"", figures:[] },

{ id:"B16", tier:"B", thread:"alloc", relevance:3, order:26,
  title:"OSDAG: Online Scheduling for Efficient Multi-Robot Collaboration",
  authors:"Thanh Nguyen Canh, Thang Tran Viet, Phuc Van Dinh, Xiem HoangVan, Nak Young Chong",
  year:2026, venue:"arXiv", het:"unclear", hetKind:"capability", appKey:"alloc", methodKey:"none", hetNote:"Heterogeneity not confirmed from metadata — check the paper before citing it as such.",
  cite:"Canh et al., 2026", bibkey:"canh2026osdag",
  gist:"Online scheduling over task dependency graphs for multi-robot collaboration.",
  useFor:"Check for overlap before making any precedence-related claim; very recent.",
  url:"https://arxiv.org/abs/2606.15255", pdf:"B16_OSDAG_OnlineScheduling_Canh_2026.pdf",
  code:"", badge:"Very recent",
  platforms:"Multi-robot", simulator:"Simulation", hardware:"No", rl:"No",
  learned:"Nothing — online DAG scheduling.", supplied:"Task dependency graph.",
  summary:"Online scheduling over task dependency graphs for multi-robot collaboration.",
  why:"Check the overlap before you make any precedence-related novelty claim.",
  caveats:[], reading:"", figures:[] },

{ id:"B12", tier:"B", thread:"alloc", relevance:3, order:27,
  title:"Graph-based Decentralized Task Allocation for Multi-Robot Target Localization",
  authors:"Juntong Peng, Hrishikesh Viswanath, Aniket Bera", year:2023, venue:"arXiv",
  het:"no", hetKind:"none", appKey:"search", methodKey:"attn", hetNote:"Sensing robots are interchangeable.",
  cite:"Peng, Viswanath & Bera, 2023", bibkey:"peng2023graph",
  gist:"Learned graph-based decentralized allocation where the task is localising targets.",
  useFor:"One of the few papers coupling allocation with information gathering — worth citing next to your core claim.",
  url:"https://arxiv.org/abs/2309.08896", pdf:"B12_GraphDecentralTaskAlloc_Peng_2023.pdf", code:"", badge:"",
  platforms:"Multi-robot", simulator:"Simulation", hardware:"No", rl:"Yes",
  learned:"Graph-based decentralized allocation for target localization.",
  supplied:"Sensing model.",
  summary:"Decentralized allocation where the task is finding things — allocation and information gathering in the same problem.",
  why:"One of the few Tier-B papers where allocation and information gathering are coupled, which is your central mechanic.",
  caveats:[], reading:"", figures:[] },

{ id:"B08", tier:"B", thread:"alloc", relevance:2, order:28,
  title:"Heterogeneous Multi-robot Task Allocation for Long-Endurance Missions in Dynamic Scenarios",
  authors:"Alvaro Calvo, Jesus Capitan", year:2024, venue:"arXiv",
  het:"yes", hetKind:"physical", appKey:"inspect", methodKey:"none",
  cite:"Calvo & Capitan, 2024", bibkey:"calvo2024heterogeneous",
  gist:"Heterogeneous allocation under battery and recharging constraints over long missions.",
  useFor:"Cite once Crazyflie endurance becomes a modelled constraint rather than an experimental nuisance.",
  url:"https://arxiv.org/abs/2411.02062", pdf:"B08_HetMRTA_LongEndurance_Calvo_2024.pdf", code:"", badge:"",
  platforms:"Heterogeneous UAV/UGV", simulator:"Simulation", hardware:"No", rl:"No",
  learned:"Nothing.", supplied:"Recharging and endurance models.",
  summary:"Allocation under battery/recharging constraints over long missions.",
  why:"Read if Crazyflie flight time becomes a first-class constraint — which, at ~7 minutes, it will.",
  caveats:[], reading:"", figures:[] },

{ id:"B05", tier:"B", thread:"aerial", relevance:3, order:29,
  title:"Stronger Together: Air-Ground Robotic Collaboration Using Semantics",
  authors:"Ian D. Miller, Fernando Cladera, Trey Smith, Camillo Jose Taylor, Vijay Kumar", year:2022, venue:"arXiv / RA-L",
  het:"yes", hetKind:"physical", appKey:"inspect", methodKey:"perception",
  cite:"Miller et al., 2022", bibkey:"miller2022stronger",
  gist:"A UAV builds a semantic map that a ground robot localises against and navigates with, in field experiments.",
  useFor:"Cite as field evidence that aerial-to-ground information transfer is a real mechanic, solved classically.",
  url:"https://arxiv.org/abs/2206.14289", pdf:"B05_StrongerTogether_AirGroundSemantics_Miller_2022.pdf", code:"", badge:"",
  platforms:"UAV + UGV", simulator:"Field experiments", hardware:"Yes", rl:"No",
  learned:"Nothing — semantic mapping and registration.", supplied:"Semantic segmentation models.",
  summary:"A UAV builds a semantic map that a ground robot then localises against and uses to navigate.",
  why:"The information-transfer mechanic you want, solved classically and in the field. Good evidence that the mechanic is real, not a simulator artefact.",
  caveats:[], reading:"", figures:[] },

{ id:"B04", tier:"B", thread:"aerial", relevance:3, order:30,
  title:"Cooperative Aerial-Ground Multi-Robot System for Automated Construction Tasks",
  authors:"Marko Križmančić, Barbara Arbanas, Tamara Petrović, Frano Petric, Stjepan Bogdan", year:2022, venue:"arXiv / RA-L",
  het:"yes", hetKind:"physical", appKey:"assembly", methodKey:"none",
  cite:"Krizmancic et al., 2022", bibkey:"krizmancic2022cooperative",
  gist:"UAV and UGV cooperate on construction/assembly with explicit scheduling, in Gazebo and on hardware.",
  useFor:"Cite as a non-learning Gazebo aerial-ground system with genuine handover dependencies.",
  url:"https://arxiv.org/abs/2204.13926", pdf:"B04_AerialGroundConstruction_Krizmancic_2022.pdf", code:"", badge:"Uses Gazebo",
  platforms:"UAV + UGV", simulator:"Gazebo", hardware:"Yes", rl:"No",
  learned:"Nothing — scheduling and coordination.", supplied:"Task model and controllers.",
  summary:"Aerial and ground robots cooperate on an assembly/construction task with explicit scheduling.",
  why:"A Gazebo-based aerial–ground system with real handover-style dependencies, done without learning.",
  caveats:[], reading:"", figures:[] },

{ id:"B06", tier:"B", thread:"aerial", relevance:3, order:31,
  title:"Active Metric-Semantic Mapping by Multiple Aerial Robots",
  authors:"Xu Liu, Ankit Prabhu, Fernando Cladera, Ian D. Miller et al.", year:2022, venue:"arXiv / ICRA",
  het:"no", hetKind:"none", appKey:"inspect", methodKey:"none", hetNote:"A team of aerial robots of the same type.",
  cite:"Liu et al., 2022", bibkey:"liu2022active",
  gist:"Multiple UAVs actively select viewpoints to build a metric-semantic map efficiently.",
  useFor:"Cite from the active-perception side when motivating why choosing where to look is itself a decision.",
  url:"https://arxiv.org/abs/2209.08465", pdf:"B06_ActiveMetricSemanticMapping_Liu_2022.pdf", code:"", badge:"",
  platforms:"Multiple aerial robots", simulator:"Field", hardware:"Yes", rl:"No",
  learned:"Nothing — active viewpoint selection.", supplied:"Mapping stack.",
  summary:"Multiple UAVs actively choose viewpoints to build a metric-semantic map efficiently.",
  why:"The active-perception side of your value-of-information question: how the mapping community decides where to look next.",
  caveats:[], reading:"", figures:[] },

{ id:"B10", tier:"B", thread:"aerial", relevance:3, order:32,
  title:"Continuous Deep Hierarchical Reinforcement Learning for Ground-Air Swarm Shepherding",
  authors:"Hung The Nguyen, Tung Duy Nguyen, Vu Phi Tran, Matthew Garratt et al.", year:2020, venue:"arXiv",
  het:"yes", hetKind:"physical", appKey:"herding", methodKey:"hrl",
  cite:"Nguyen et al., 2020", bibkey:"nguyen2020continuous",
  gist:"Hierarchical RL for a UAV shepherding a ground swarm.",
  useFor:"A second hierarchical aerial-ground RL reference point; low priority.",
  url:"https://arxiv.org/abs/2004.11543", pdf:"B10_GroundAirSwarmShepherding_Nguyen_2020.pdf", code:"", badge:"",
  platforms:"UAV + ground swarm", simulator:"Simulation", hardware:"No", rl:"Yes",
  learned:"Hierarchical RL policies for ground-air shepherding.", supplied:"Low-level controllers.",
  summary:"A UAV shepherds a ground swarm using a hierarchical policy over sub-behaviours.",
  why:"Hierarchical RL with aerial–ground heterogeneity, if you want a second architectural reference point.",
  caveats:[], reading:"", figures:[] },

{ id:"B11", tier:"B", thread:"aerial", relevance:2, order:33,
  title:"Hierarchical Policy-Gradient Reinforcement Learning for Multi-Agent Shepherding Control of Non-Cohesive Targets",
  authors:"Stefano Covone, Italo Napolitano, Francesco De Lellis, Mario di Bernardo", year:2025, venue:"arXiv",
  het:"no", hetKind:"none", appKey:"herding", methodKey:"hrl", hetNote:"The herder team is homogeneous.",
  cite:"Covone et al., 2025", bibkey:"covone2025hierarchical",
  gist:"Cleaner recent hierarchical policy-gradient formulation of multi-agent shepherding.",
  useFor:"Architecture reference only.",
  url:"https://arxiv.org/abs/2504.02479", pdf:"B11_HierPG_Shepherding_Covone_2025.pdf", code:"", badge:"",
  platforms:"Multi-agent herders", simulator:"Simulation", hardware:"No", rl:"Yes",
  learned:"Hierarchical policy-gradient shepherding control.", supplied:"Low-level dynamics.",
  summary:"A cleaner, more recent hierarchical formulation of the shepherding control problem.",
  why:"Architecture reference only.", caveats:[], reading:"", figures:[] },

{ id:"B13", tier:"B", thread:"tamp", relevance:3, order:34,
  title:"Hierarchical Temporal Logic Task and Motion Planning for Multi-Robot Systems",
  authors:"Zhongqi Wei, Xusheng Luo, Changliu Liu", year:2025, venue:"arXiv",
  het:"yes", hetKind:"capability", appKey:"alloc", methodKey:"none",
  cite:"Wei, Luo & Liu, 2025", bibkey:"wei2025hierarchical",
  gist:"Hierarchical LTL specifications drive combined task and motion planning for robot teams.",
  useFor:"Cite as the formal-methods alternative when explaining why you chose a learned planner.",
  url:"https://arxiv.org/abs/2504.18899", pdf:"B13_HierTemporalLogicTAMP_Wei_2025.pdf", code:"", badge:"",
  platforms:"Multi-robot manipulators", simulator:"Simulation", hardware:"No", rl:"No",
  learned:"Nothing — formal synthesis.", supplied:"LTL specification.",
  summary:"Hierarchical LTL specifications drive combined task and motion planning for robot teams.",
  why:"The symbolic alternative to your learned planner. Worth knowing so you can say precisely why you are not doing this.",
  caveats:[], reading:"", figures:[] },

{ id:"B14", tier:"B", thread:"tamp", relevance:3, order:35,
  title:"Simultaneous Task Allocation and Planning for Multi-Robots under Hierarchical Temporal Logic Specifications",
  authors:"Xusheng Luo, Changliu Liu", year:2024, venue:"arXiv / T-RO",
  het:"yes", hetKind:"capability", appKey:"alloc", methodKey:"none",
  cite:"Luo & Liu, 2024", bibkey:"luo2024simultaneous",
  gist:"Allocation and planning solved simultaneously under hierarchical temporal-logic specifications.",
  useFor:"Cite to show the allocation-planning coupling is also a formal-methods result, not only a learning one.",
  url:"https://arxiv.org/abs/2401.04003", pdf:"B14_STAP_HierTemporalLogic_Luo_2024.pdf", code:"", badge:"",
  platforms:"Multi-robot", simulator:"Simulation", hardware:"No", rl:"No",
  learned:"Nothing.", supplied:"Hierarchical LTL specification.",
  summary:"Allocation and planning solved together under hierarchical temporal-logic specs.",
  why:"Shows that 'allocation and planning are coupled' is also a formal-methods result, not only a learning one.",
  caveats:[], reading:"", figures:[] },

{ id:"B15", tier:"B", thread:"systems", relevance:2, order:36,
  title:"MOSAIC: Multi-Robot On-site Shared Analytics Information and Computing",
  authors:"Joshua Vander Hook, Federico Rossi, Tiago Vaquero, Martina Troesch et al.", year:2021, venue:"arXiv (NASA JPL)",
  het:"yes", hetKind:"capability", appKey:"field", methodKey:"none",
  cite:"Vander Hook et al., 2021", bibkey:"vanderhook2021mosaic",
  gist:"Joint scheduling of tasks and shared computation across a heterogeneous field robot team.",
  useFor:"Cite only if you widen heterogeneity to include compute and bandwidth.",
  url:"https://arxiv.org/abs/2112.06879", pdf:"B15_MOSAIC_MultiRobotSharedComputing_VanderHook_2021.pdf", code:"", badge:"",
  platforms:"Heterogeneous field robots", simulator:"Analysis / field", hardware:"Yes", rl:"No",
  learned:"Nothing.", supplied:"Task and compute models.",
  summary:"Joint scheduling of tasks and shared computation across a heterogeneous field robot team.",
  why:"A reminder that heterogeneity includes compute and bandwidth, not just actuation. Orthogonal, but a useful framing.",
  caveats:[], reading:"", figures:[] }
];

window.GAPS = {
  caps:[
    {name:"Heterogeneous capabilities", by:["A01","A02","A03","A04","A05","A06","A07","A08","A09","A10","A11","A14","A16","A17"]},
    {name:"Capability conditioning / transfer to unseen teams", by:["A03","A05","A06","A08"]},
    {name:"Task precedence / dependencies", by:["A01","A04","A05"]},
    {name:"Asynchronous skill durations", by:["A10","A11","A15"]},
    {name:"Partial observability with an explicit belief", by:["A11","A15"]},
    {name:"Value of information — decides <em>whether</em> to inspect", by:["A11"]},
    {name:"Enabling actions that change the environment for future tasks", by:[]},
    {name:"Learned (RL) high-level policy", by:["A03","A10","A11","A16","A17"]},
    {name:"Physics simulator", by:["A02","A04","A07","A09","A16"]},
    {name:"Real hardware", by:["A07","A09","A10","A14","A16","A17"]}
  ],
  established:[
    "Heterogeneous cooperation itself — thoroughly covered (A01–A08, A14, A16, A17).",
    "Capability/trait conditioning and generalisation to unseen team compositions — CASH (A06), E-ITAGS (A05), HeteroMRTA (A03).",
    "Task dependencies and precedence in <em>learned</em> allocation — SADCHER (A04).",
    "Learning coordination policies above supplied controllers — Xiao 2022 (A10), Liu 2017 (A11).",
    "Aerial perception guiding ground manipulation — A09, B05, B06.",
    "Sim-trained heterogeneous manipulation policies deployed on hardware — A16."
  ],
  opening:[
    "a planner that decides <strong>whether to inspect at all</strong>, weighing cost against downstream value;",
    "<strong>enabling actions</strong> that change the environment for <em>future</em> tasks (opening a shortcut) rather than directly achieving a goal;",
    "<strong>genuine asynchrony</strong> across flight, navigation and manipulation skills of very different duration;",
    "a <strong>belief representation</strong> where unknown ≠ false, evaluated in physics simulation."
  ],
  caveat:"This is a <em>candidate</em> direction to investigate. The literature does not support claiming that heterogeneous cooperation, capability conditioning, or task dependencies are individually new."
};

window.PROBLEM = {
  title:"Learning When Robots Should Help: Contingent Planning for Heterogeneous Robot Teams",
  question:"Can a learned planner coordinate information gathering, manipulation, and transport across heterogeneous robots, while adapting its action sequence and assignments to uncertainty and execution outcomes?",
  robots:[
    {name:"Crazyflie 2.1", role:"Flies to viewpoints, inspects regions with a simulated camera, reports visible objects and route conditions, returns to a landing location."},
    {name:"LoCoBot PX100", role:"Navigates, inspects locally, picks/places small objects, loads and unloads the TurtleBot, operates a reachable button controlling a shortcut."},
    {name:"TurtleBot 4", role:"Navigates, inspects locally, transports objects on an added passive tray, rendezvouses with the LoCoBot."}
  ],
  constraints:[
    "PX100: 4 DoF, ~300 mm reach, ~50 g stated working payload with extension restrictions — keep objects small and surfaces reachable.",
    "The tray is an explicit addition to the TurtleBot model.",
    "Loading <em>and</em> unloading both require the LoCoBot, including a rendezvous at the destination. This dependency must be represented in the planning problem."
  ],
  decisions:[
    {q:"Inspect or commit", d:"Should the drone check a likely sample location, or should the LoCoBot start moving there immediately?"},
    {q:"Deliver directly or cooperate", d:"Should the LoCoBot carry one sample to the station, or load the TurtleBot and retrieve another sample before their unloading rendezvous?"},
    {q:"Improve access or take a detour", d:"Should the LoCoBot spend time operating a shortcut that will benefit several <em>future</em> deliveries?"},
    {q:"Serve urgently or batch", d:"Deliver a priority sample now, or wait for more?"},
    {q:"Continue or replan", d:"If a grasp fails or a route is blocked, which ongoing assignments should remain in place?"}
  ],
  designRule:"The environment must contain instances where <em>each</em> alternative is preferable. Otherwise the learned solution collapses into a fixed sequence of “drone searches → arm picks → carrier transports.”",
  observation:[
    "Provide perfect object labels and poses <strong>within each robot's field of view</strong>; keep unseen regions unknown.",
    "Unknown facts must remain <strong>distinct from false facts</strong>.",
    "Action masks must not leak hidden simulator information.",
    "Ordinary deterministic PDDL alone is insufficient — you need an explicit belief representation or a contingent/replanning mechanism."
  ],
  formulation:[
    "Centralized planner over temporally extended skills, keeping existing navigation, flight and manipulation controllers underneath.",
    "High-level action <code>a = (robot or coalition, skill, arguments)</code> — e.g. <code>inspect(drone, room_2)</code>, <code>load(locobot, turtlebot, sample_3, rendezvous_1)</code>.",
    "Each skill exposes preconditions, expected effects, duration, success/failure result, and occupied resources.",
    "Event-driven semi-Markov decision points: decide when a robot becomes available, an observation arrives, or execution fails.",
    "State as a graph: robots and capabilities, objects and beliefs, rooms/routes/access conditions, goals and deadlines."
  ],
  targets:[
    {t:"High-level skill policy", w:"Next robot–skill assignment, conditioned on belief and ongoing actions.", why:"Straightforward first RL baseline."},
    {t:"Value function / heuristic guiding search", w:"Expected downstream cost or value of candidate plans.", why:"Suits a planning-oriented researcher; supports explicit lookahead. <strong>Aim here</strong>, with the policy as comparison. Caveat: a learned heuristic does not automatically preserve optimality guarantees."}
  ],
  reward:"Mission completion and elapsed time as the main signals, with penalties for failed execution and resource use. <strong>Do not reward every inspection</strong> — that teaches unnecessary exploration. Inspection must be justified by downstream value.",
  stages:[
    "Establish the physical task — one robot of each type, four rooms, six small objects, a reachable tray, reliable load/unload. Start fully observed.",
    "Introduce meaningful uncertainty — hide sample locations outside local observations. Compare adaptive inspection against “inspect everything” and “never inspect”.",
    "Introduce optional interventions — add the button-operated shortcut. Vary its cost and how many future trips benefit.",
    "Learn and test generalization — hold out layouts, object counts, capability values, and eventually team compositions."
  ],
  baselines:["Direct LoCoBot delivery (no cooperation)","Fixed robot roles","Greedy allocator","A temporal/replanning planner receiving the same observations","A fully-informed planner — kept as a separately labelled reference, not a fair baseline"],
  metrics:["Mission success","Completion time","Robot waiting time","Planning latency","Performance on held-out instances"],
  firstResult:"A planner that reliably switches between inspecting, delivering directly, coordinating handoffs, and improving access <em>as their relative costs change</em>."
};

window.HARDWARE = [
  ["LoCoBot PX100 specifications","https://docs.trossenrobotics.com/interbotix_xslocobots_docs/specifications/locobot_px100.html"],
  ["Interbotix PX100 arm specifications","https://docs.trossenrobotics.com/interbotix_xsarms_docs/specifications/px100.html"],
  ["TurtleBot 4 — mechanical / payloads","https://turtlebot.github.io/turtlebot4-user-manual/mechanical/payloads.html"],
  ["Crazyflie 2.1 product page","https://www.bitcraze.io/crazyflie-2-1/"],
  ["PX4 support for Crazyflie 2.1","https://docs.px4.io/main/en/complete_vehicles_mc/crazyflie21"],
  ["HeteroMRTA code","https://github.com/marmotlab/HeteroMRTA"],
  ["COHERENT code","https://github.com/MrKeee/COHERENT"],
  ["Spatial Intention Maps — code, videos, policies","https://spatial-intention-maps.cs.princeton.edu/"]
];
